# Generated by Django 2.0.3 on 2018-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=1000)),
                ('animeType', models.CharField(blank='False', choices=[('TV', 'TV/Series'), ('Movie', 'Movie'), ('Special', 'Special'), ('OVA', 'OVA')], default='TV', max_length=10)),
                ('episodes', models.IntegerField()),
                ('rating', models.FloatField()),
                ('members', models.IntegerField()),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
    ]
