# Generated by Django 2.0.3 on 2018-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0002_auto_20180328_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeType',
            field=models.CharField(blank='False', choices=[('TV', 'TV/Series'), ('Movie', 'Movie'), ('Special', 'Special'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Music', 'Music'), ('UNKNOWN', 'Unknown')], default='TV', max_length=10),
        ),
    ]
