# Generated by Django 2.0.3 on 2018-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0003_auto_20180330_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='photoCover',
            field=models.ImageField(null=True, upload_to='img/covers', verbose_name='cover photo'),
        ),
    ]
