# Generated by Django 2.0.3 on 2018-03-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0004_anime_photocover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeType',
            field=models.CharField(blank='False', choices=[('TV/Series', 'TV/Series'), ('Movie', 'Movie'), ('Special', 'Special'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Music', 'Music'), ('Unknown', 'Unknown')], default='TV/Series', max_length=10),
        ),
        migrations.AlterField(
            model_name='anime',
            name='photoCover',
            field=models.ImageField(blank=True, null=True, upload_to='img/covers', verbose_name='cover photo'),
        ),
    ]
