# Generated by Django 2.0.3 on 2018-03-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0005_auto_20180330_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='photoCover',
            field=models.ImageField(blank=True, null=True, upload_to='./img/covers', verbose_name='cover photo'),
        ),
    ]
