# Generated by Django 2.0.3 on 2018-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0007_auto_20180331_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='photoCover',
            field=models.ImageField(blank=True, null=True, upload_to='animeapp/img/covers', verbose_name='cover photo'),
        ),
    ]
